name: Secret Scanning

on:
  pull_request:
    branches: [main, dev]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--no-git -r ."

